image: node:20

pages:
  stage: deploy
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --configuration production --base-href "/$CI_PROJECT_NAME/"
    - mkdir -p public
    - cp -r dist/*/* public/
  artifacts:
    paths:
      - public
  only:
    - main